<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container65ebOjE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container65ebOjE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container65ebOjE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container65ebOjE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container65ebOjE\App_KernelDevDebugContainer([
    'container.build_hash' => '65ebOjE',
    'container.build_id' => 'a3f61c55',
    'container.build_time' => 1621963137,
], __DIR__.\DIRECTORY_SEPARATOR.'Container65ebOjE');
