<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKJ7iL0d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKJ7iL0d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKJ7iL0d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKJ7iL0d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKJ7iL0d\App_KernelDevDebugContainer([
    'container.build_hash' => 'KJ7iL0d',
    'container.build_id' => '0cd7c4e6',
    'container.build_time' => 1622151238,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKJ7iL0d');
